# encoding: UTF-8

require 'csv'

file2title = {
"out2.csv" => "CAUSE OF DEATH IN BRISTOL MUNICIPAL DISTRICT (1870 – 1900)" ,
"out3.csv" => "CAUSE OF DEATH IN BRISTOL UNION (1838 – 1855)" ,
"out4.csv" => "CAUSE OF DEATH IN BRISTOL UNION (1856 – 1900)" ,
"out5.csv" => "CAUSE OF DEATH  IN BRISTOL (UNION AND CITY AND COUNTY) (1901 – 1939)" ,
"out6.csv" => "CAUSE OF DEATH  IN CITY AND COUNTY OF BRISTOL (1940 – 1978)" ,
"out7.csv" => "CAUSE OF DEATH  IN CITY OF BRISTOL (1979 – 1995)" ,
"out8.csv" => "CAUSE OF DEATH  IN BEDMINSTER UNION AND REGISTRATION DISTRICT (1838 – 1855)" ,
"out9.csv" => "CAUSE OF DEATH  IN BEDMINSTER UNION AND REGISTRATION DISTRICT (1856 – 1900)" ,
"out10.csv" => "CAUSE OF DEATH  IN LONG ASHTON UNION AND REGISTRATION DISTRICT (1901 – 1920)" ,
"out11.csv" => "CAUSE OF DEATH  IN CLIFTON UNION AND REGISTRATION DISTRICT (1838 – 1855)" ,
"out12.csv" => "CAUSE OF DEATH  IN CLIFTON (BARTON REGIS FROM 14 MARCH 1877) UNION AND REGISTRATION DISTRICT (1856-1900)" ,
"out13.csv" => "CAUSE OF DEATH  IN BARTON REGIS UNION AND REGISTRATION DISTRICT (1901 – 1904)" ,
"out14.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY AND COUNTY OF BRISTOL (1884 – 1918)" ,
"out15.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY AND COUNTY OF BRISTOL (1919 – 1939)" ,
"out16.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY AND COUNTY OF BRISTOL (1940 – 1949)" ,
"out17.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY AND COUNTY OF BRISTOL (1950 – 1967)" ,
"out18.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY AND COUNTY OF BRISTOL (1968 – 1984)" ,
"out19.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN THE CITY OF BRISTOL (1985 – 1995)" ,
"out20.csv" => "NOTIFICATION OF INFECTIOUS DISEASE IN LONG ASHTON UNION AND REGISTRATION DISTRICT (1921 – 1930)"
 }

indata = false
years = nil
CSV.foreach(ARGV[0], { :skip_blanks => true }) do |row|

	if row.size > 1 && row[1].to_i > 1000
		indata = !indata
		years = row
	elsif indata
		rowname = row[0]

		row.each_with_index do |val, i|
			puts "#{file2title[ARGV[0]]}, #{rowname}, #{years[i]}, #{val}" unless val == rowname
		end
	end
end